# Generated by Django 4.2.14 on 2024-10-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_category_options_category_subscribers_and_more'),
        ('news', '0003_news'),
    ]

    operations = [
    ]
