# Generated by Django 4.2.14 on 2024-10-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_merge_20241007_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RemoveField(
            model_name='article',
            name='type',
        ),
    ]
